# ─────────────────────────────────────────────────────────────────────────────
# PeakForm — Cloud Build config
#
# Used by Cloud Run's native "Connect to GitHub" feature.
# In the Cloud Console: Cloud Run → your service → Edit → Triggers →
# "Continuously deploy from a repository" → point to this repo.
# Cloud Build will run these steps on every push to the configured branch.
#
# Substitutions set automatically by Cloud Build:
#   $_SERVICE_NAME   set in trigger config  (e.g. peakform)
#   $_REGION         set in trigger config  (e.g. us-central1)
#   $_AR_HOSTNAME    set in trigger config  (e.g. us-central1-docker.pkg.dev)
#   $_AR_REPO        set in trigger config  (e.g. peakform)
#   $PROJECT_ID      injected automatically
#   $SHORT_SHA       first 7 chars of the commit SHA
#
# Secret Manager vars (optional — set via Cloud Build trigger substitutions
# or link to Secret Manager in the Cloud Run service settings):
#   _APP_PASSWORD
#   _ANTHROPIC_API_KEY
# ─────────────────────────────────────────────────────────────────────────────

substitutions:
  _SERVICE_NAME:  peakform
  _REGION:        us-central1
  _AR_HOSTNAME:   us-central1-docker.pkg.dev
  _AR_REPO:       peakform
  _GCS_BUCKET:    ""   # Set to a GCS bucket name for cross-device state persistence

steps:

  # ── 1. Pull previous image for layer caching ───────────────────────────────
  - name: gcr.io/cloud-builders/docker
    id: pull-cache
    entrypoint: bash
    args:
      - -c
      - |
        docker pull \
          $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/app:latest || true

  # ── 2. Build ───────────────────────────────────────────────────────────────
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - --cache-from
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/app:latest
      - --tag
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/app:$SHORT_SHA
      - --tag
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/app:latest
      - .

  # ── 3. Push both tags ─────────────────────────────────────────────────────
  - name: gcr.io/cloud-builders/docker
    id: push-sha
    args: [push, $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/app:$SHORT_SHA]

  - name: gcr.io/cloud-builders/docker
    id: push-latest
    args: [push, $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/app:latest]

  # ── 4. Deploy to Cloud Run ────────────────────────────────────────────────
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/app:$SHORT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
      - --port=8080
      - --set-env-vars=PEAKFORM_GCS_BUCKET=$_GCS_BUCKET
      - --quiet

images:
  - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/app:$SHORT_SHA
  - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/app:latest

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8   # faster builds

timeout: 1200s
